### ISSUE TITLE
Link not working

### ISSUE THREAD

**Issue by Gertwillem** [scia-garage/OpenAPIComplexExampleWithADMCSharp#1]
this link : For methods and objects of so called ADM - documentation is "here"
isnt working

https://docs.calatrava.scia.net/html/9900284a-b4b6-405e-b157-630e24129caf.htm#!

**Comment by jarabroz** [comment]
Hi @Gertwillem,

here is link http://docs.calatrava.scia.net/html/9900284a-b4b6-405e-b157-630e24129caf.htm

**Comment by someparsa** [comment]
Hello, The link is not working for one hour and there is no chance to bring it up, anyway. It returns connection run-out. Even checked to see whether I can open it with other internet services or browsers, turned off the fire-walls, changed my device, etc. None of these helped.
Could you please unit the server of help pages and bring all of them to your main help website domain? Currently, part of the help files are on help.scia.net and the ADM is on docs.calatrava.scia.net; this while the latter suffers from occasional drops while the former is up on service and healthy. Moreover, the help files for ADM are not delivered while the software is installed. Thank you
